name: resume
description: Flutter resume application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

# Network
  dio: ^4.0.6
  url_launcher: ^6.1.6

# Storage
  shared_preferences: ^2.0.15

# State management
  flutter_bloc: ^8.1.1
  bloc_concurrency: ^0.2.0

# Core
  get_it: ^7.2.0
  intl: ^0.17.0
  fluro: ^2.0.3
  funvas: ^0.1.7

# Localization
  easy_localization: ^3.0.0
  easy_localization_loader: ^1.0.1+1

# UI
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  animated_text_kit: ^4.2.2

# Annotation
  injectable: ^1.5.3
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.10.0"

# Code generation
  icons_launcher: ^2.0.5
  build_runner: ^2.1.5
  json_serializable: ^6.3.1
  freezed: ^2.2.0
  injectable_generator: ^1.5.3

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app_logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/app_logo.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/

  fonts:
    - family: Horizon
      fonts:
        - asset: assets/fonts/Horizon.otf

    - family: Invetero
      fonts:
        - asset: assets/fonts/invetero-Regular.ttf